# Usar una imagen base de OpenJDK
FROM openjdk:17-jdk-alpine

# Directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el archivo JAR generado en la etapa de construcción al contenedor
COPY target/producto-gateway-0.0.1-SNAPSHOT.jar /app/producto-gateway.jar

# Comando para ejecutar la aplicación Spring Boot
ENTRYPOINT ["java", "-jar", "producto-gateway.jar"]

# Exponer el puerto en el que la aplicación escuchará
EXPOSE 8080