server:
  port: 8080  # Puerto en el que se ejecuta el API Gateway

spring:
  cloud:
    gateway:
      routes:
        - id: productos
          uri: http://localhost:8081  # URL de tu microservicio de productos
          predicates:
            - Path=/api/productos/**  # Ruta que se debe redirigir

  application:
    name: producto-gateway

  # Configuración de CORS (opcional)
  globalcors:
    cors-configurations:
      '[/**]':
        allowed-origins: '*'
        allowed-methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowed-headers:
          - '*'
